// src/config/permissions.js
export const permissions = {
  admin: {
    dashboard: { view: true, edit: true },
    hrMaster: { view: true },
    show: { view: true, edit: true },
    employeeMaster: { view: true, edit: true, delete: true },
    departmentMaster: { view: true, edit: true },
    shiftTime: { view: true, edit: true },
    grouproster: { view: true, edit: true },
    resignation: { view: true, edit: true },
    termination: { view: true, edit: true },
    userManagement: { view: true, edit: true, delete: true },
    allowanceDeduction: { view: true },
    createNewAllowance: { view: true, edit: true },
    createNewDeduction: { view: true, edit: true },
    loans: { view: true },
    viewLoans: { view: true, edit: true },
    employeeLoan: { view: true, edit: true },
    salaryProcess: { view: true },
    SalaryProcessPage: { view: true, edit: true },
    SalaryPage: { view: true },
    timeAttendance: { view: true },
    TimeCard: { view: true, edit: true },
    Overtime: { view: true, edit: true },
    leaveMaster: { view: true, edit: true },
    leaveApproval: { view: true, approve: true },
    hrLeaveApproval: { view: true, approve: true },
    noPayManagement: { view: true, edit: true },
    leavecalendar: { view: true },
    reports: { view: true },
    utilities: { view: true },
    pmsDashboard: { view: true },
    performanceReviews: { view: true, edit: true },
    kpis: { view: true, edit: true },
    myKPIs: { view: true },
  },
  manager: {
    dashboard: { view: true },
    hrMaster: { view: true },
    show: { view: true },
    employeeMaster: { view: true },
    departmentMaster: { view: true },
    leaveApproval: { view: true, approve: true },
    hrLeaveApproval: { view: true, approve: true },
    leaveMaster: { view: true },
    leavecalendar: { view: true },
    reports: { view: true },
    pmsDashboard: { view: true },
    performanceReviews: { view: true, edit: true },
    kpis: { view: true, edit: true },
    myKPIs: { view: true },
  },
  employee: {
    dashboard: { view: true },
    hrMaster: { view: true },
    show: { view: true },
    leaveMaster: { view: true, edit: true },
    leavecalendar: { view: true },
    myKPIs: { view: true },
  },
};
